### PR TITLE
Neo Blockchain Scrapper

### PR DESCRIPTION
**Pull request by bounty-js**
Once the neonode service is started It fetches the chain.acc.zip(3.6GB) only for the first time the docker is run, if saved file is not used then it takes days to sync the chain. volume is mounted from /home/srv/neo So data  is saved in this location and docker can be stopped and started and the chain will continue from before block.
Once the neo service is started it makes connection to the neonode service and  waits for the chain to sync, once the chain is synchronized it fetches neo at address AQVh2pG732YvtNaxEGkQUei3YA4cvo7d2i and substracts it from 100000000 and sends the supply to dia client

### CODE REVIEW

**Comment by frranck** [comment]
Hi, 
I added a missing service for the scraper,
here https://github.com/diadata-org/api-golang/tree/pr/32
 but its a bit weird, it downloads the file

3562050K .......... .......... .......... .......... .......... 99% 27.3M 0s
3562100K .......... .......... .......... .......... .......... 99% 98.2M 0s
3562150K                                                       100%  345G=48m44s

2018-09-02 18:39:52 (1.19 MB/s) - 'chain.acc.zip' saved [3647641785/3647641785]

NEO-CLI Version: 2.8.0.0

neo> franck@ubuntuF:~/go/src/github.com/diadata-org/api-golang/blockchain-scrapers$ 

and then the container restarts, and it download the file from scratch again..

**Comment by bounty-js** [comment]
Hi @frranck second time new container is created or the same container restarted?

**Comment by bounty-js** [comment]
Hi @frranck  thanks for adding the neo service
Earlier I have test the image with `docker run -it <image>` then it worked fine. But after seeing your error I tried it from docker-compose then I got exited with error 0. It is a problem with docker compose https://github.com/docker/compose/issues/3896 . however, adding `tty: true` in the neonode service fixed it. 
As you mentioned it downloaded the file twice. Earlier I was checking for the file chain.acc.zip if not exists  then download. So when ever docker stops and starts it should not download, but when new docker is created again from the image then it downloads the file again. So I have changed it to check for "CURRENT" file in the volume, so as long as the volume has chain data irrespective of the container it will not download the file again. Here is the docker file https://github.com/bounty-js/neocli-mainnet-docker. 
But when you see "CURRENT" file in "/home/srv/neo" and if you know that chain height is very low than chain.acc.zip then it is better to rm all files in '"/home/srv/neo" and run a new docker instance so that it downloads the file and updates the blocks.
Now I am running the service and it took ~1hr to download the file and 2 hrs and still it is updating the chain and the volume became 5.2GB
I will push the code once the chain is updated and neo client is able to scrap it.

**Comment by bounty-js** [comment]
Hi @frranck 
I think it should work fine
It's been 3 hrs and still running. This is the tail of /home/srv/neo/LOG
`2018/09/03-05:21:09.252348 7f6b8b328700 Generated table #95021: 4415 keys, 2112923 bytes
2018/09/03-05:21:09.320331 7f6b8b328700 Generated table #95022: 5232 keys, 1300037 bytes
2018/09/03-05:21:09.409331 7f6b8b328700 Generated table #95023: 9234 keys, 2120342 bytes
2018/09/03-05:21:09.509331 7f6b8b328700 Generated table #95024: 9691 keys, 2120894 bytes
2018/09/03-05:21:09.598306 7f6b8b328700 Generated table #95025: 6752 keys, 1490819 bytes
2018/09/03-05:21:09.687283 7f6b8b328700 Generated table #95026: 9974 keys, 2118848 bytes
2018/09/03-05:21:09.742986 7f6b8b328700 Generated table #95027: 18412 keys, 876888 bytes
2018/09/03-05:21:09.776571 7f6b8b328700 Generated table #95028: 3278 keys, 140418 bytes
2018/09/03-05:21:09.854409 7f6b8b328700 Generated table #95029: 7282 keys, 265996 bytes
2018/09/03-05:21:09.854452 7f6b8b328700 Compacted 1@0 + 7@1 files => 12547165 bytes
2018/09/03-05:21:09.921182 7f6b8b328700 compacted to: files[ 0 9 88 540 2535 0 0 ]
2018/09/03-05:21:09.924267 7f6b8b328700 Delete type=2 #94980
2018/09/03-05:21:09.924714 7f6b8b328700 Delete type=2 #94992
2018/09/03-05:21:09.925352 7f6b8b328700 Delete type=2 #94979
2018/09/03-05:21:09.925793 7f6b8b328700 Delete type=2 #94974
2018/09/03-05:21:09.926397 7f6b8b328700 Delete type=2 #94976
2018/09/03-05:21:09.926868 7f6b8b328700 Delete type=2 #94978
2018/09/03-05:21:09.927144 7f6b8b328700 Delete type=2 #94975
2018/09/03-05:21:09.927604 7f6b8b328700 Delete type=2 #94977
2018/09/03-05:21:09.928360 7f6b8b328700 Compacting 1@1 + 10@2 files
2018/09/03-05:21:10.010750 7f6b8b328700 Generated table #95030: 1518 keys, 2109909 bytes
2018/09/03-05:21:10.088648 7f6b8b328700 Generated table #95031: 1515 keys, 2109030 bytes
2018/09/03-05:21:10.210983 7f6b8b328700 Generated table #95032: 1481 keys, 2110036 bytes
2018/09/03-05:21:10.211033 7f6b8b328700 Level-0 table #95034: started
2018/09/03-05:21:10.333276 7f6b8b328700 Level-0 table #95034: 2422064 bytes OK
2018/09/03-05:21:10.372338 7f6b8b328700 Delete type=0 #94991
2018/09/03-05:21:10.455563 7f6b8b328700 Generated table #95035: 1502 keys, 2106812 bytes`

Volume size is 6GB, I am not sure still how much time it is going to take. So I have pushed the code, do let me know if you find errors and my docker node is still running.

**Pull request merged**
