### PR TITLE
implement Simex REST scraper

### LINKED ISSUE #13: Simex API Scraping
We are looking for a Go developer that can provide scrapers of a websocket API. If our collaboration is productive we also offer tasks that include scraping of REST APIs. We reliably want to get trades in realtime from cryptocurrency exchanges. This trade information is then written into our databases using a specific format. We have an existing framework for this which allows us to parametrize the scraper. We work with Go and expect that the scrapers will work concurrently and efficiently.

We will provide the necessary documentation for the task and introduce you to our framework. https://simex.global/en/docs/introduction

Set-up instruction for the task can be found under: http://docs.diadata.org/scraper.html
Documentation

### PR DESCRIPTION
**Pull request by PumpkingWok**
##### Description

- This PR implement a new scraper into the code for Simex exchange.
- Since Simex does not seem to implement a Websocket, it uses REST API.
- I have created a support struct into the code, i did not want modify so much classic scraper object.
- For now i have added 14 pairs to json file, it seems there are not so much top pairs in this exchange.

##### Checklist

- [X] Changes don't break existing behavior

##### Affected core subsystem(s)

Core

##### Testing

I tested the code into Mac OS environment, with go 1.10.3

##### Refers/Fixes

Fixes #13

### CODE REVIEW

**Comment by kaythxbye** [comment]
Thanks for your submission @PumpkingWok! We look into it and after we verified everything works we will close the issue in Gitcoin.

**Comment by PumpkingWok** [comment]
HI @kaythxbye, thank you too. 
Ask to me without problems if you have doubt regard the code.

**Comment by frranck** [comment]
@PumpkingWok I'm getting this error:
invalid character '<' looking for beginning of value

**Comment by PumpkingWok** [comment]
Hi @frranck ,
When do you encounter this error ?
When do you run scraper.go after build it ?
Thanks

**Comment by PumpkingWok** [comment]
Hi @frranck,
I have encounter this error too.I'm looking for resolve it.

**Comment by PumpkingWok** [comment]
Hi @frranck, 
The error occurred after the first API call to retrieve all pairs, return <nil> now, from there there is '<' invalid character.
I need to look into the code, i have just run another go file that i have developed yesterday for testing and it catch the same error. Yesterday everything went smooth, my testing file does not import external packages.Thanks and sorry

**Comment by frranck** [comment]
No worries, looking forward to your fix

**Comment by frranck** [comment]
Isn't that a bit weird for a rest api ?

**Comment by PumpkingWok** [comment]
Hi @frranck,
Now seems that they working over API service, I'm waiting that Simex dev service will contact me.
I have tried using mechanize (implement cookie) in python but nothing, i could try with selenium.
Thanks

**Comment by PumpkingWok** [comment]
Hi @frranck 
Could you test the code now ? In theory it works now, I tested it.

**Comment by PumpkingWok** [comment]
@frranck Very good, It seems that they were working on API.
If you want i can keep monitored the REST call for some days.
Thanks

**Pull request merged**
